import HomePageWrapper from "@/components/HomePageWrapper/HomePageWrapper";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Diabetes360 | Where you finally meet Diabetes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePageWrapper />
    </>
  );
}
